name: build and test

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Download LLVM src
      uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
        ref: llvmorg-11.0.0
        path: llvm-project

    - name: Build Clang/LLVM
      run: cd llvm-project; mkdir build; cd build; cmake -DLLVM_ENABLE_PROJECTS=clang -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON -G "Unix Makefiles" ../llvm; make -j

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLLVM_SRC=${{runner.workspace}}/llvm-project

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE --target test
